### ISSUE TITLE
Change logic for "update reminder time" functionality to handle inputs without `at ` prefix

### ISSUE THREAD

**Issue by arthurshir** [bubakazouba/remindmebot#67]
**Example**

Expected:
- Entering `2pm` as an input to update reminder time would result in the reminder updating its time to 2pm

Actual:
- reminder set to "now"

Image:
- <img width="439" alt="Screen Shot 2021-01-06 at 12 13 24 PM" src="https://user-images.githubusercontent.com/38710729/103805064-ac97d180-5018-11eb-8270-fe48a9c3d5f8.png">

#Bug

**Comment by bubakazouba** [comment]
Issue was fixed in PR #70, problem had nothing to do with update reminder, just the fact that `nlp/timeutils` fail when given a time and meridiem with no delimiter and no `at`
