### ISSUE TITLE
Fix bug where we are using the wrong id for location callback

### ISSUE THREAD

**Issue by arthurshir** [bubakazouba/remindmebot#85]
Logic in location callback for timezonecommand sets timezone for `ctx.from.id` but it should instead set it by `ctx.chat.id`

See line -> https://github.com/bubakazouba/remindmebot/blob/b22f77537d6ac3cd5434f936730a398926e817ab/botfunctions/timezonecommand.js#L54

Todos:
- Investigate implications of using `ctx.chat.id` there
- Figure out why using `ctx.from.id` has been working
- Make change to logic

**Comment by bubakazouba** [comment]
It was probably only working for private chats and not working for group chats
